### ISSUE TITLE
improve search results to search in all text

### ISSUE THREAD

**Issue by JonAlexandra** [alexandrainst/DanskeTestfaciliteter#7]
Make the searchfield consider all text associated with a facility.

**Comment by JonAlexandra** [comment]
Make the searchfield consider all text associated with a facility.

**Comment by MagnusHBrunbjerg** [comment]
Fuzzy-ish search has been implemented in 487688c. This allows for also getting search results that doesn't match exactly but are close, for example "brand" og "brænd", and makes sure the closest results are shown first.

Currently all facility properties that makes sense to search are searched but the data contained in these fields does not necessarily make sense to search, for example the payment type, due to the way the data is store. Reconsider the data-storage/-mapping of these fields for better searching.
